import { Product, Category } from "@/types";

// UUIDs for categories
const categoryIds = {
  pos: "a1b2c3d4-e5f6-7890-abcd-ef1234567890",
  education: "b2c3d4e5-f6a7-8901-bcde-f12345678901",
  community: "c3d4e5f6-a7b8-9012-cdef-123456789012",
  business: "d4e5f6a7-b8c9-0123-defa-234567890123",
  custom: "e5f6a7b8-c9d0-1234-efab-345678901234",
};

// UUIDs for products
const productIds = {
  bimbel: "f6a7b8c9-d0e1-2345-fabc-456789012345",
  rtrw: "a7b8c9d0-e1f2-3456-abcd-567890123456",
  pos: "b8c9d0e1-f2a3-4567-bcde-678901234567",
  printing: "c9d0e1f2-a3b4-5678-cdef-789012345678",
  inventory: "d0e1f2a3-b4c5-6789-defa-890123456789",
};

// UUIDs for images
const imageIds = [
  "e1f2a3b4-c5d6-7890-efab-901234567890",
  "f2a3b4c5-d6e7-8901-fabc-012345678901",
  "a3b4c5d6-e7f8-9012-abcd-123456789012",
  "b4c5d6e7-f8a9-0123-bcde-234567890123",
  "c5d6e7f8-a9b0-1234-cdef-345678901234",
];

export const mockCategories: Category[] = [
  {
    id: categoryIds.pos,
    name: "Kasir (POS)",
    slug: "pos",
    description: "Sistem kasir dan manajemen penjualan untuk berbagai jenis bisnis",
    icon: "ShoppingCart",
    created_at: "2024-01-01T00:00:00Z",
  },
  {
    id: categoryIds.education,
    name: "Pendidikan",
    slug: "education",
    description: "Sistem manajemen untuk lembaga pendidikan dan bimbel",
    icon: "GraduationCap",
    created_at: "2024-01-01T00:00:00Z",
  },
  {
    id: categoryIds.community,
    name: "Komunitas",
    slug: "community",
    description: "Sistem manajemen untuk RT/RW dan organisasi komunitas",
    icon: "Users",
    created_at: "2024-01-01T00:00:00Z",
  },
  {
    id: categoryIds.business,
    name: "Bisnis",
    slug: "business",
    description: "Sistem ERP dan manajemen bisnis terintegrasi",
    icon: "Building",
    created_at: "2024-01-01T00:00:00Z",
  },
  {
    id: categoryIds.custom,
    name: "Kustom",
    slug: "custom",
    description: "Solusi software kustom sesuai kebutuhan spesifik",
    icon: "Code",
    created_at: "2024-01-01T00:00:00Z",
  },
];

export const mockProducts: Product[] = [
  {
    id: productIds.bimbel,
    name: "Sistem Manajemen Bimbel",
    slug: "sistem-manajemen-bimbel",
    short_description:
      "Solusi lengkap untuk mengelola bimbel dengan pendaftaran siswa, jadwal, absensi, dan pembayaran.",
    description:
      "Sistem manajemen komprehensif yang dirancang khusus untuk bimbel dan lembaga pendidikan di Indonesia. Fitur meliputi pendaftaran siswa, penjadwalan kelas, pencatatan absensi, manajemen pembayaran, laporan kemajuan, dan notifikasi orang tua. Dibangun dengan Laravel untuk keandalan dan kemudahan perawatan.",
    price: 8000000,
    category_id: categoryIds.education,
    category: mockCategories[1],
    images: [
      {
        id: imageIds[0],
        product_id: productIds.bimbel,
        url: "https://placehold.co/800x600/fafafa/171717?text=Dashboard+Bimbel",
        alt: "Dashboard Bimbel",
        order: 0,
        created_at: "2024-01-01T00:00:00Z",
      },
      {
        id: imageIds[1],
        product_id: productIds.bimbel,
        url: "https://placehold.co/800x600/e4e4e7/171717?text=Data+Siswa",
        alt: "Data Siswa",
        order: 1,
        created_at: "2024-01-01T00:00:00Z",
      },
      {
        id: imageIds[2],
        product_id: productIds.bimbel,
        url: "https://placehold.co/800x600/d4d4d8/171717?text=Jadwal+Kelas",
        alt: "Jadwal Kelas",
        order: 2,
        created_at: "2024-01-01T00:00:00Z",
      },
      {
        id: imageIds[3],
        product_id: productIds.bimbel,
        url: "https://placehold.co/800x600/a1a1aa/ffffff?text=Pembayaran",
        alt: "Pembayaran",
        order: 3,
        created_at: "2024-01-01T00:00:00Z",
      },
      {
        id: imageIds[4],
        product_id: productIds.bimbel,
        url: "https://placehold.co/800x600/71717a/ffffff?text=Laporan",
        alt: "Laporan",
        order: 4,
        created_at: "2024-01-01T00:00:00Z",
      },
    ],
    features: [
      "Pendaftaran dan profil siswa",
      "Penjadwalan kelas dan alokasi ruangan",
      "Pencatatan absensi",
      "Manajemen pembayaran dengan laporan",
      "Laporan kemajuan dan penilaian",
      "Portal orang tua untuk monitoring",
      "Manajemen pengajar",
      "Laporan keuangan bulanan",
    ],
    tech_stack: ["Laravel", "MySQL", "Bootstrap", "JavaScript"],
    demo_url: "#",
    is_featured: true,
    status: "active",
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
  },
  {
    id: productIds.rtrw,
    name: "Sistem Manajemen RT/RW",
    slug: "sistem-manajemen-rt-rw",
    short_description:
      "Solusi digital untuk pengelolaan warga, iuran, dan pembuatan surat menyurat.",
    description:
      "Sistem manajemen RT/RW modern yang mendigitalisasi administrasi lingkungan. Kelola data warga dengan mudah, pantau iuran bulanan, buat surat-surat resmi, dan fasilitasi komunikasi antar warga. Sesuai dengan kebutuhan administrasi Indonesia.",
    price: 6000000,
    category_id: categoryIds.community,
    category: mockCategories[2],
    images: [
      {
        id: "d1e2f3a4-b5c6-7890-1234-567890abcdef",
        product_id: productIds.rtrw,
        url: "https://placehold.co/800x600/f4f4f5/171717?text=RT-RW",
        alt: "Dashboard RT/RW",
        order: 0,
        created_at: "2024-01-01T00:00:00Z",
      },
    ],
    features: [
      "Database warga dengan silsilah keluarga",
      "Pencatatan iuran bulanan",
      "Generate kwitansi otomatis",
      "Template surat resmi (SK, domisili, dll)",
      "Manajemen acara dan rapat",
      "Data kontak darurat",
      "Laporan keuangan transparan",
      "Tampilan responsif mobile-friendly",
    ],
    tech_stack: ["Laravel", "MySQL", "Livewire", "Tailwind CSS"],
    demo_url: "#",
    is_featured: true,
    status: "active",
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
  },
  {
    id: productIds.pos,
    name: "Sistem Kasir Retail",
    slug: "sistem-kasir-retail",
    short_description:
      "Sistem POS dengan manajemen stok, laporan penjualan, dan multi-cabang.",
    description:
      "Solusi POS lengkap untuk bisnis retail. Kelola penjualan, stok, supplier, dan pelanggan dari satu dashboard. Mendukung multi-cabang, manajemen karyawan, dan laporan komprehensif.",
    price: 7000000,
    category_id: categoryIds.pos,
    category: mockCategories[0],
    images: [
      {
        id: "e2f3a4b5-c6d7-8901-2345-678901abcdef",
        product_id: productIds.pos,
        url: "https://placehold.co/800x600/e4e4e7/171717?text=POS",
        alt: "Dashboard POS",
        order: 0,
        created_at: "2024-01-01T00:00:00Z",
      },
    ],
    features: [
      "Pencarian produk dan checkout cepat",
      "Manajemen stok dengan alert stok rendah",
      "Manajemen multi-cabang",
      "Role dan hak akses karyawan",
      "Laporan penjualan harian dan bulanan",
      "Database pelanggan",
      "Cetak struk dan faktur",
      "Backup dan restore data",
    ],
    tech_stack: ["Laravel", "MySQL", "Vue.js", "Bootstrap"],
    demo_url: "#",
    is_featured: true,
    status: "active",
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
  },
  {
    id: productIds.printing,
    name: "Sistem Manajemen Percetakan",
    slug: "sistem-manajemen-percetakan",
    short_description:
      "Kelola pesanan cetak, pantau status produksi, dan atur antrian dengan efisien.",
    description:
      "Sistem manajemen khusus untuk bisnis percetakan. Lacak pesanan dari masuk hingga selesai, kelola antrian produksi, atur variasi harga, dan simpan riwayat pelanggan. Mendukung berbagai jenis cetak: digital, offset, dan large format.",
    price: 5500000,
    category_id: categoryIds.business,
    category: mockCategories[3],
    images: [
      {
        id: "f3a4b5c6-d7e8-9012-3456-789012abcdef",
        product_id: productIds.printing,
        url: "https://placehold.co/800x600/d4d4d8/171717?text=Printing",
        alt: "Dashboard Percetakan",
        order: 0,
        created_at: "2024-01-01T00:00:00Z",
      },
    ],
    features: [
      "Input pesanan dengan upload file",
      "Manajemen antrian produksi",
      "Kalkulator harga untuk jenis cetak berbeda",
      "Riwayat pesanan pelanggan",
      "Tracking pengiriman",
      "Inventori bahan baku",
      "Laporan produksi harian",
      "Generate invoice",
    ],
    tech_stack: ["Laravel", "MySQL", "jQuery", "Bootstrap"],
    demo_url: "#",
    is_featured: false,
    status: "active",
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
  },
  {
    id: productIds.inventory,
    name: "Sistem Manajemen Stok",
    slug: "sistem-manajemen-stok",
    short_description:
      "Pantau level stok, kelola supplier, dan dapatkan notifikasi stok menipis.",
    description:
      "Sistem manajemen stok yang simpel tapi powerful. Pantau level stok real-time, kelola informasi supplier, terima notifikasi stok menipis, dan generate laporan inventori komprehensif. Cocok untuk bisnis kecil hingga menengah.",
    price: 5000000,
    category_id: categoryIds.business,
    category: mockCategories[3],
    images: [
      {
        id: "a4b5c6d7-e8f9-0123-4567-890123abcdef",
        product_id: productIds.inventory,
        url: "https://placehold.co/800x600/a1a1aa/ffffff?text=Inventory",
        alt: "Dashboard Stok",
        order: 0,
        created_at: "2024-01-01T00:00:00Z",
      },
    ],
    features: [
      "Manajemen produk dan kategori",
      "Pencatatan stok masuk/keluar",
      "Notifikasi stok menipis",
      "Manajemen supplier",
      "Pembuatan purchase order",
      "Riwayat penyesuaian stok",
      "Laporan valuasi inventori",
      "Siap integrasi barcode",
    ],
    tech_stack: ["Laravel", "MySQL", "Alpine.js", "Tailwind CSS"],
    demo_url: null,
    is_featured: true,
    status: "coming_soon",
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
  },
];
